### ISSUE TITLE
NMF solver failure on iteration 1

### ISSUE THREAD

**Issue by thomas4g** [smallk/smallk#7]
When running `hierclust` on a large set of data (235k words, 10 million docs) with any amount of clusters (tried as few as 5, as many as 20), I get the error 

```
    NMF solver failure on iteration 1
```

I also received this error running `nmf` on anything bigger than a 1 million x 1 million matrix. Could this simply be due to system constraints? I have 16 GB RAM & 4-core 2.5 GHz Intel i7 on a MacBook. 

The exact output of the command is:

```
~/git/smallk$ ./hierclust/bin/hierclust --matrixfile test.mtx --dictfile dictionary.txt --clusters 5
WARNING: Could not achieve THREAD_MULTIPLE support.
loading dictionary...
loading matrix...

     Command line options:

                    height: 235886
                     width: 10000000
                matrixfile: test.mtx
                   initdir:
                  dictfile: dictionary.txt
                assignfile: assignments_5.csv
                    format: XML
                  treefile: tree_5.xml
                  clusters: 5
                       tol: 0.0001
                    outdir:
                   miniter: 5
                   maxiter: 5000
                  maxterms: 5
                maxthreads: 8
                unbalanced: 0.1
           trial_allowance: 3
                      flat: 0
                   verbose: 1

SystemSolveW: singular matrix
        NMF solver failure on iteration 1

Root node factorization failed, retrying with new initializers...
SystemSolveW: singular matrix
        NMF solver failure on iteration 1

Root node factorization failed, retrying with new initializers...
SystemSolveW: singular matrix
        NMF solver failure on iteration 1

Root node factorization failed, retrying with new initializers...
terminate called after throwing an instance of 'std::runtime_error'
  what():  HierNMF2: root node factorization failed after three attempts
[csr-wf-l09:67109] *** Process received signal ***
[csr-wf-l09:67109] Signal: Abort trap: 6 (6)
[csr-wf-l09:67109] Signal code:  (0)
[csr-wf-l09:67109] [ 0] 0   libsystem_platform.dylib            0x00007fff9986352a _sigtramp + 26
[csr-wf-l09:67109] [ 1] 0   ???                                 0x0000000000000001 0x0 + 1
[csr-wf-l09:67109] [ 2] 0   libsystem_c.dylib                   0x00007fff934446e7 abort + 129
[csr-wf-l09:67109] [ 3] 0   libstdc++.6.dylib                   0x00000001095bcdd7 _ZN9__gnu_cxx27__verbose_terminate_handlerEv + 327
[csr-wf-l09:67109] *** End of error message ***
Abort trap: 6
```

**Comment by bldrake** [comment]
Thomas,


Did you run the preprocessing code on the sparse matrix (proprocess_tf)? This tells me that the input matrix may be numerically singular.

The preprocessing code removes any problematic, nearly zero rows or columns from the .mtx file.

If you have done this, please let me know.

Thanks!
Barry

________________________________

**Comment by thomas4g** [comment]
Barry,
Apologies, I should have clarified: both matrices I tested with (with `hierclust` and with `nmf`) were matrices generated by `matrixgen`; specifically, the command:

`./matrixgen/bin/matrixgen --height 235886 --width 10000000 --type SPARSE --filename test.mtx`

So, it wasn't _real_ data, per se, as I just wanted an idea of how fast `nmf` and `hierclust` could handle large matrices. 

Thanks for your help!
- Thomas

**Comment by bldrake** [comment]
Thomas,


My apologies as well. It can happen with real text data that we see zero rows or columns. But,

rank deficiency is never a problem. Even for just the nonnegative least squares problem alone, since

we use block coordinate descent, we are always solving the problem in the feasible region. Thus, rank deficiency is 'carved out'. We have a paper proving this applied to a real-world  chemical detection problem.


The fact that the error generated doesn't make sense for your problem concerns me. Thanks for letting us know about this.


Cheers!

Barry


________________________________

**Comment by thomas4g** [comment]
Thanks Barry. I'll be trying the same commands on a more powerful box and will report results. 
Let me know if there's any way I can help debug. 

Best,
Thomas
